### ISSUE TITLE
README issues

### ISSUE THREAD

**Issue by hyang66** [joyceliaoo/eggs#2]
## Statement of Problem 
this was mentioned in class, but the wording of "starting position" is a little ambiguous
## Recursive Abstraction
same thing as above (w/ "starting position")
the meaning of "one less stepping stone" could be confusing (where is there one less?)
## Base Case
this was also kinda mentioned in class but smaller base cases could make programming easier :)

**Comment by tangym27** [comment]
## English or pseudocode description of algorithm
the phrase "pair routine" is confusing 
"mark" the current stepping stone was also ambiguous (but in class we said mark=drop a wall)

**Comment by jcheung7** [comment]
Thank you for the feedback. We updated the README to be more perspicuous and modified the algorithm to correct those issues.

**Comment by joyceliaoo** [comment]
Please let us know if any part is still unclear. Thanks guys!
